name: Build and deploy .NET Core application to Web App CarvedRock-MVC
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: CarvedRock-MVC
  AZURE_WEBAPP_PACKAGE_PATH: CarvedRock-MVC\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: CarvedRock-MVC
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY\MVC\CarvedRock-MVC }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY\MVC\CarvedRock-MVC }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY\MVC\CarvedRock-MVC }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY\MVC\CarvedRock-MVC }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.CarvedRock_MVC_EC16 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
